#!/usr/bin/env python3
import json
import logging
import re
from pathlib import Path
from datetime import datetime

import github_publisher
from config_loader import load_config

log = logging.getLogger("output_router")

_OUTPUT_MENU = {int(k): v for k, v in load_config()["output_menu"].items()}

# Same single-defang-point convention as soc-skill-cloud's §6.7 (one bracket
# at a domain's final period before the TLD, one bracket at an IP's last
# octet separator, plus http(s) -> hxxp(s) for a full URL) -- applied here in
# code rather than left to the model, since this footer/header text is
# deterministically built from cve_data, not generated by the AI. Only used
# on reference/citation URLs (the Sources footer, the severity-discrepancy
# source link); never on a Suricata rule's or hunting query's own functional
# match syntax, which the AI prompt is separately instructed to leave literal.
_IP_RE = re.compile(r"\b(\d{1,3}\.\d{1,3}\.\d{1,3})\.(\d{1,3})\b")


def _defang_url(url: str) -> str:
    if not url:
        return url
    defanged = url.replace("https://", "hxxps://", 1).replace("http://", "hxxp://", 1)
    scheme_end = defanged.find("://")
    if scheme_end != -1:
        scheme_end += 3
        path_start = defanged.find("/", scheme_end)
        domain_end = path_start if path_start != -1 else len(defanged)
        domain = defanged[scheme_end:domain_end]
        last_dot = domain.rfind(".")
        if last_dot != -1 and not _IP_RE.fullmatch(domain):
            domain = domain[:last_dot] + "[.]" + domain[last_dot + 1:]
        defanged = defanged[:scheme_end] + domain + defanged[domain_end:]
    # Also defang an IP appearing later in the path (e.g. an IP-lookup URL).
    return _IP_RE.sub(lambda m: f"{m.group(1)}[.]{m.group(2)}", defanged)


_URL_TOKEN_RE = re.compile(r"https?://[^\s<>\"')\]]+")
_BARE_DOMAIN_RE = re.compile(
    r"\b(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+"
    r"(?:com|net|org|io|gov|edu|mil|info|biz|co|dev|app|ai|to|xyz|ru|cn|de|uk|us)\b"
)
# Only ever call on 'advisory'/'ioc_list' output -- prose and reference
# material where every IP/domain/URL is safe to defang uniformly. NEVER
# call on 'signatures'/'hunting_queries' output: those are functional
# Suricata rule / CrowdStrike-nfdump query syntax, and defanging a literal
# IP or domain there breaks the rule/query itself.
_OUTPUT_TYPES_SAFE_TO_DEFANG = {"advisory", "ioc_list"}


def _defang_text(text: str) -> str:
    """Code-side safety net on top of the AI's own defanging instruction
    (config/vuln-skill.yaml's system_prompt) -- live testing showed the
    model reliably swaps http(s) -> hxxp(s) but inconsistently brackets a
    domain's TLD period, and when it DOES bracket one, it isn't always the
    last period (e.g. "nvd[.]nist.gov" instead of "nvd.nist[.]gov"). Left
    alone, that partial/misplaced bracket survives past the URL pass below
    (which only touches a plain, unbracketed period) and the domain pass
    then finds a *different* plain-dot-terminated TLD match earlier in the
    same string, adding a second bracket on top -- a real double-defang
    bug caught via live testing (CVE-2021-44228 -> "nvd[.]nist[.]gov").
    Normalizing every existing "[.]" back to "." first makes this
    idempotent: the output is always exactly the same single-bracket
    result regardless of what (if anything) the model already did.
    URLs are matched (and fully defanged via _defang_url) before the bare
    domain/IP passes below, so a domain/IP already inside one isn't
    independently re-matched and double-processed."""
    text = text.replace("[.]", ".").replace("hxxps://", "https://").replace("hxxp://", "http://")
    text = _URL_TOKEN_RE.sub(lambda m: _defang_url(m.group(0)), text)

    def _domain_sub(m):
        domain = m.group(0)
        last_dot = domain.rfind(".")
        return domain[:last_dot] + "[.]" + domain[last_dot + 1:]

    text = _BARE_DOMAIN_RE.sub(_domain_sub, text)
    text = _IP_RE.sub(lambda m: f"{m.group(1)}[.]{m.group(2)}", text)
    return text


def _defang_body(body: str, output_type: str) -> str:
    """Applies _defang_text to the AI-generated body, scoped by output
    type: advisory/ioc_list are pure prose/reference material, safe to
    defang in full. signatures/hunting_queries are functional Suricata
    rule / CrowdStrike-nfdump query artifacts -- defanging their match/
    query syntax would break them, so only their own trailing "## Sources"
    section (never part of the functional rule/query body, and observed
    live to get inconsistently and sometimes badly mangled by the model's
    own attempt at this -- e.g. "2.14.1" -> "2[.]14[.]1" in a PoC URL
    path) gets the same deterministic treatment."""
    if output_type in _OUTPUT_TYPES_SAFE_TO_DEFANG:
        return _defang_text(body)
    idx = body.find("## Sources")
    if idx == -1:
        return body
    return body[:idx] + _defang_text(body[idx:])


class OutputRouter:
    def __init__(self, base_dir: Path):
        self.base_dir = base_dir

    def clean_remote(self) -> int:
        """Wipe every file under outputs/ in the GitHub repo (single commit) —
        the remote-side counterpart to the local outputs/ folder wipe, so
        GitHub never accumulates files across runs."""
        return github_publisher.clean_outputs()

    def save(self, output_num: int, cve_data: dict, result: dict) -> Path:
        cve_id = cve_data.get("cve_id", "UNKNOWN").replace("-", "_")
        output_type = result.get("output_type", f"output_{output_num}")
        menu_entry = _OUTPUT_MENU.get(output_num, {})
        ext = menu_entry.get("extension", ".txt")
        subdir = menu_entry.get("output_dir", "misc")

        folder = self.base_dir / subdir
        folder.mkdir(parents=True, exist_ok=True)

        # One canonical filename per CVE+output-type — no timestamp. Re-running
        # against the same CVE overwrites this file (locally and, via SHA-based
        # update in github_publisher, on GitHub too) instead of piling up a new
        # timestamped file on every run. The generation time still lives in the
        # header below. review_needed status also stays out of the filename —
        # a REVIEW_NEEDED_ prefix would give the same CVE+type two possible
        # paths, defeating the point of a single canonical file.
        filename = f"{cve_id}_{output_type}{ext}"
        filepath = folder / filename

        # Governs blockquote-vs-comment header/footer style below -- keyed off
        # the entry's own "preview" setting (what the web UI actually renders
        # this as), not the file extension. hunting_queries/ioc_list are both
        # ".txt" with preview:markdown, so they need the SAME blockquote
        # treatment ".md" gets, or every "#"-prefixed header/footer line
        # renders as its own giant H1 once the body goes through full
        # Markdown rendering (web-bugs-and-tweaks.md #51 -- found live: a
        # hunting_queries file's own header rendered as nine stacked H1s).
        is_markdown_preview = menu_entry.get("preview") == "markdown"
        header = self._build_header(cve_data, result, output_num, is_markdown_preview)
        footer = self._build_sources_footer(cve_data, is_markdown_preview)
        body = _defang_body(result.get("content", ""), output_type)
        content = header + "\n\n" + body + footer

        if result.get("review_needed"):
            if is_markdown_preview:
                content += f"\n\n**REVIEW_NEEDED**\nError: {result.get('error', 'unknown')}"
            else:
                content += f"\n\n# REVIEW_NEEDED\n# Error: {result.get('error', 'unknown')}"

        filepath.write_text(content)
        log.info(f"Saved: {filepath}")
        self._log_run(cve_data, output_num, result, filepath)

        repo_path = f"outputs/{subdir}/{filename}"
        commit_msg = f"Vuln-Skill: {output_type} for {cve_data.get('cve_id', 'UNKNOWN')}"
        github_publisher.publish(str(filepath), repo_path, commit_msg)

        return filepath

    def _build_header(self, cve_data: dict, result: dict, output_num: int, is_markdown_preview: bool) -> str:
        tags_str = " ".join(f"[{t}]" for t in cve_data.get("tags", []))
        fields = [
            f"CVE:       {cve_data.get('cve_id', '')}",
            f"Product:   {cve_data.get('product', '')}",
            f"Tags:      {tags_str}",
            f"Score:     {cve_data.get('composite_score', 0)}",
            f"Tier:      {cve_data.get('tier_label', '')}",
        ]

        disc = cve_data.get("context", {}).get("severity_discrepancy") or {}
        if disc.get("has_discrepancy"):
            fields.append(
                f"SEVERITY DISCREPANCY: NVD/vulnx says {disc['nvd_score']} "
                f"({disc['nvd_severity']}) — CVE.org (CNA, v{disc['cna_version']}) says "
                f"{disc['cna_score']} ({disc['cna_severity']}). See {_defang_url(disc['cna_source_url'])}"
            )

        fields += [
            f"Generated: {datetime.utcnow().isoformat()}Z",
            "Generated by Vuln-Skill. Draft output for analyst review and validation before operational use.",
            f"Status:    {'REVIEW_NEEDED' if result.get('review_needed') else 'OK'}",
        ]

        menu_entry = _OUTPUT_MENU.get(output_num, {})
        label = menu_entry.get("label", result.get("output_type", ""))
        title = f"VULN-SKILL GENERATED OUTPUT — {label.upper()}"
        if is_markdown_preview:
            # '#'-prefixed lines are H1 headings in Markdown, not comments — each
            # would render as its own giant heading (web-bugs-and-tweaks.md #51/
            # #52 -- found live on both counts: hunting_queries/ioc_list's own
            # "#"-prefixed header rendering as nine stacked H1s). A ">" blockquote
            # was tried instead, but _render_safe_markdown HTML-escapes the text
            # BEFORE running it through Markdown (deliberately, so literal HTML
            # in AI-echoed content can't execute) -- html.escape() turns a
            # leading ">" into "&gt;", which Markdown's blockquote parser no
            # longer recognizes, so the whole header rendered as one plain
            # escaped-looking paragraph instead of an indented blockquote. Bold
            # (`**`) and a horizontal rule (`---`) both use characters
            # html.escape() never touches, so they're the only formatting that
            # actually survives the escape-then-render pipeline intact -- normal
            # body-text size, still visually set apart via the rule below it.
            lines = [f"**{title}**", ""] + fields + ["", "---"]
            return "\n".join(lines)

        lines = [f"# {title}"] + [f"# {f}" for f in fields] + ["# ---"]
        return "\n".join(lines)

    def _build_sources_footer(self, cve_data: dict, is_markdown_preview: bool) -> str:
        """Deterministic source list, guaranteed present regardless of whether
        the model's own citations (if any) match or are complete."""
        sources = cve_data.get("context", {}).get("sources") or []
        if not sources:
            return ""

        if is_markdown_preview:
            # Same heading level and plain list style as the AI's own "## Sources"
            # section, so this reads as the same size/font, not a giant heading
            # per '#'-prefixed line.
            lines = ["", "## Sources (Vuln-Skill-verified)", ""]
            for i, src in enumerate(sources, 1):
                lines.append(f"[{i}] {src['label']} — {_defang_url(src['url'])}")
            return "\n".join(lines) + "\n"

        # '#' is a genuine comment character in .txt/.yml/.rules — safe as-is.
        lines = ["", "# --- Sources (Vuln-Skill-verified) ---"]
        for i, src in enumerate(sources, 1):
            lines.append(f"# [{i}] {src['label']} — {_defang_url(src['url'])}")
        return "\n".join(lines) + "\n"

    def _log_run(self, cve_data: dict, output_num: int, result: dict, filepath: Path) -> None:
        usage = result.get("usage") or {}
        log_entry = {
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "cve_id": cve_data.get("cve_id"),
            "product": cve_data.get("product"),
            "output_num": output_num,
            "output_type": result.get("output_type"),
            "composite_score": cve_data.get("composite_score"),
            "tags": cve_data.get("tags"),
            "success": result.get("success"),
            "review_needed": result.get("review_needed", False),
            "error": result.get("error") if result.get("review_needed") else None,
            "input_tokens": usage.get("input"),
            "output_tokens": usage.get("output"),
            "cache_write_tokens": usage.get("cache_write"),
            "cache_read_tokens": usage.get("cache_read"),
            "cost": usage.get("cost"),
            "filepath": str(filepath),
        }
        log_path = Path("/opt/vuln-skill/logs/runs.jsonl")
        with open(log_path, "a") as f:
            f.write(json.dumps(log_entry) + "\n")
